integrated sonarcloud and change job to docker

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -5,40 +5,26 @@ on:
     branches: [ "main" ]
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    strategy:
-      max-parallel: 4
-      matrix:
-        python-version: [3.9]
-
+  build-and-test:
     steps:
-    - uses: actions/checkout@v3
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v3
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: Install Dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
+    - uses: actions/checkout@v4
 
-  test:
-    needs: build
+    - name: Build the Docker image
+      run: docker-compose up --build -d
+
+    - name: Run tests
+      run: sudo docker-compose run --rm backend-ds2 python manage.py test --verbosity=2 && echo "✅ All tests passed!" || echo "❌ Some tests failed."
+
+  sonarcloud:
+    needs: build-and-test
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
-    - name: Test
-      run: |
-        python manage.py test --verbosity=2 && echo "✅ All tests passed!" || echo "❌ Some tests failed."
-
-  deploy:
-    needs: test
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: Deploy
+      - uses: actions/checkout@v4
+        with:
+          # Disabling shallow clone is recommended for improving relevancy of reporting
+          fetch-depth: 0
+      - name: SonarCloud Scan
+        uses: sonarsource/sonarcloud-github-action@master
         env:
-          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
-        run: |
-          curl "$deploy_url"
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
